### ISSUE TITLE
Autoplay With Sound

### ISSUE THREAD

**Issue by erockdotdev** [fmedinac/react-facebook-player#10]
By default it seems that videos start off muted. I don't see a prop for configuring that. Any thoughts on how I can set the default behavior to play a video with sound?

**Comment by petrgazarov** [comment]
Facebook player widget implements autoplay with sound muted, according to description in the docs:

> data-autoplay
Automatically start playing the video when the page loads. The video will be played without sound (muted). People can turn on sound via the video player controls. This setting does not apply to mobile devices. Can be false or true.

You can call the API on the player to unmute it. E.g.

```
onPlayerReady = (_id, player) => {
  player.unmute();
  player.play();
}

render() {
  return (
    <FacebookPlayer
      // ...
      onReady={this.onPlayerReady}
    />
  )
}
```

Reference API docs: https://developers.facebook.com/docs/plugins/embedded-video-player/api

**Comment by erockdotdev** [comment]
Thank you for your response. This worked perfectly!
