### ISSUE TITLE
Unnecessary youtube-player dependency

### ISSUE THREAD

**Issue by isBatak** [fmedinac/react-facebook-player#2]
Is there any need for youtube-player dependency in package.json?
[https://github.com/fmedinac/react-facebook-player/blob/master/package.json#L26](https://github.com/fmedinac/react-facebook-player/blob/master/package.json#L26)

**Comment by fmedinac** [comment]
Good catch, it came from [React Youtube](https://github.com/troybetz/react-youtube) which this project was based on. Removed on ad032fb7cf893e9d3954561f314a577edcbf0adc.
