### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by andreas-pihlstrom** [fmedinac/react-facebook-player#4]
Thank you so much for this component. Was wondering if you know if there is a React Native version out there anywhere? If not, would you consider porting this to work for React Native as well? :)

**Comment by fmedinac** [comment]
No, it will not work on React Native without using WebView.

Unfortunately I don't have much experience on Java and/or Swift/ObjC to help you out with that. Sorry.

**Comment by CheaChan** [comment]
It is supported by React Native Webview?

**Comment by fmedinac** [comment]
@CheaChan I don't think so. This project is pretty out-dated, so I'm sorry but I recommend finding another solution.

**Comment by CheaChan** [comment]
@fmedinac thanks.
