### ISSUE TITLE
Player does not unsubscribe unmounted components

### ISSUE THREAD

**Issue by petrgazarov** [fmedinac/react-facebook-player#7]
`FB.Event.subscribe('xfbml.ready')` is called once for every time the component is mounted. `FB.Event.unsubscribe` should be called before unmounting the component. Right now, the listener lives on and tries to run the code despite the component being unmounted. See [commit](https://github.com/petrgazarov/react-facebook-player/commit/80f767f00f11a0280ea2cc3ecd8b8a1539ca3f3b) where I fixed the issue.

**Comment by fmedinac** [comment]
@petrgazarov please open a PR. ;)
